import type { Role } from './roles';

const ALL_NAV = [
  'dashboard',
  'alarm-dashboard',
  'dispatch',
  'calendar',
  'customers',
  'customer-profile',
  'chat',
  'team-chat',
  'leads',
  'photos',
  'documents',
  'deals',
  'projects',
  'work-orders',
  'tickets',
  'inspections',
  'tasks',
  'warehouses',
  'distributors',
  'purchase-orders',
  'products',
  'packages',
  'site-inventory',
  'estimates',
  'invoices',
  'statements',
  'transactions',
  'time-attendance',
  'user-management',
  'reports',
  'settings',
  'technician-portal',
  'customer-portal',
  'product-central',
];

export const ROLE_PAGES: Record<Role, string[]> = {
  admin: ALL_NAV,

  accounting: [
    'dashboard',
    'customers',
    'customer-profile',
    'estimates',
    'invoices',
    'statements',
    'transactions',
    'reports',
    'settings',
    'documents',
    'user-management',
    'product-central',
    'inspections',
  ],

  sales_manager: [
    'dashboard',
    'customers',
    'customer-profile',
    'leads',
    'deals',
    'calendar',
    'chat',
    'team-chat',
    'documents',
    'photos',
    'estimates',
    'reports',
    'projects',
    'product-central',
  ],

  sales: [
    'dashboard',
    'customers',
    'customer-profile',
    'leads',
    'deals',
    'calendar',
    'chat',
    'documents',
    'photos',
    'estimates',
    'product-central',
  ],

  csr: [
    'dashboard',
    'customers',
    'customer-profile',
    'tickets',
    'work-orders',
    'inspections',
    'leads',
    'dispatch',
    'calendar',
    'chat',
    'team-chat',
    'alarm-dashboard',
    'documents',
    'product-central',
  ],

  dispatcher: [
    'dashboard',
    'dispatch',
    'calendar',
    'work-orders',
    'tickets',
    'inspections',
    'chat',
    'team-chat',
    'customers',
    'customer-profile',
    'technician-portal',
    'alarm-dashboard',
    'time-attendance',
    'product-central',
  ],

  tech_manager: [
    'dashboard',
    'dispatch',
    'calendar',
    'work-orders',
    'inspections',
    'time-attendance',
    'team-chat',
    'chat',
    'technician-portal',
    'reports',
    'customers',
    'customer-profile',
    'products',
    'packages',
    'site-inventory',
    'warehouses',
    'purchase-orders',
    'tickets',
    'product-central',
  ],

  tech: [
    'dashboard',
    'technician-portal',
    'calendar',
    'time-attendance',
    'chat',
    'products',
    'packages',
    'product-central',
  ],

  limited_tech: [
    'dashboard',
    'technician-portal',
    'calendar',
    'time-attendance',
    'chat',
    'product-central',
  ],
};

export function canAccessPage(role: Role, page: string): boolean {
  return ROLE_PAGES[role].includes(page);
}
