/*
  # Add Payment Token to Invoices

  ## Summary
  Adds a unique `payment_token` column to the `invoices` table so each invoice
  can be accessed via a public payment link (e.g. #/pay/<token>). Tokens are
  short, URL-safe strings generated automatically for every existing invoice.

  ## Modified Tables
  - `invoices`
    - `payment_token` (text, unique, nullable) - short random token for public payment links

  ## Security
  - Existing anon SELECT policy already covers invoices.
  - Anon SELECT on `invoice_line_items` and `companies` already exists.
  - No new write policies for anon — payment page is read-only for invoice data.

  ## Notes
  1. Backfills every existing invoice with a unique 12-char alphanumeric token.
  2. Future invoices can have tokens generated by the app when sending.
*/

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'invoices' AND column_name = 'payment_token'
  ) THEN
    ALTER TABLE invoices ADD COLUMN payment_token text UNIQUE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_invoices_payment_token ON invoices(payment_token);

-- Backfill existing invoices with unique tokens
UPDATE invoices
SET payment_token = substr(md5(id::text || random()::text), 1, 12)
WHERE payment_token IS NULL;
